name: unique_name_generator
description: Random name generator based on dictionaries.
version: 1.0.0
homepage: https://github.com/abichinger/unique-name-generator

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
